repos:
  - repo: https://github.com/Vimjas/vint
    rev: v0.4a3
    hooks:
      - id: vint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or: [yaml, json]

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.17.1
    hooks:
      - id: stylua
