#!/usr/bin/env bash

TYPE=start
AUTHOR=$1
NAME=$2

if [ -z $AUTHOR ] || [ -z $NAME ]; then
  echo $0: Installs vim plugins from GitHub.
  echo The following fetches the repository from https://www.github.com/\$AUTHOR/\$NAME
  echo and installs it into pack/plugins/\$TYPE/\$NAME. The TYPE defaults to \"start\".
  echo
  echo Usage: $0 \$AUTHOR \$NAME [\$TYPE]
  echo
  echo If the plugin contains a folder named \"doc\" the containing helptags are generated.
  exit -1
fi

if [ ! -z $3 ]; then
  TYPE=$3
fi

git submodule add https://github.com/$AUTHOR/$NAME pack/plugins/$TYPE/$NAME

if [ -d pack/plugins/$TYPE/$NAME/doc ]; then
  vim -u NONE -c "helptags pack/plugins/$TYPE/$NAME/doc" -c q
fi

