#!/usr/bin/env bash

FOLDER=$1

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo $0: Updates a submodules and regenerates helptags.
  echo
  echo Usage: $0 \$FOLDER
  exit -1
fi

git submodule update --recursive --remote $FOLDER
if [ -d $FOLDER/doc ]; then
  vim -u NONE -c "helptags $FOLDER/doc" -c q
fi
