#!/usr/bin/env bash

git submodule update --recursive --remote

echo "Remember that LanguageClient-neovim/ needs a rebuild via its ./install.sh script!" # That's something git submodules can't do ...
